---
- name: Pull SQL Docker image
  docker_image:
    name: "{{ sql_container_image }}"
    source: pull

- name: Create SQL container
  docker_container:
    name: "{{ sql_container_name }}"
    image: "{{ sql_container_image }}"
    ports:
      - "{{ sql_container_port }}:{{ sql_container_port }}"
    env:
      MARIADB_USER: "{{ sql_default_username }}"
      MARIADB_DATABASE: "{{ sql_default_database }}"
      MARIADB_PASSWORD: "{{ sql_default_password }}"
      MARIADB_ROOT_PASSWORD: "{{ sql_root_password }}"
    volumes:
      - sql_data:/var/lib/mysql
    networks_cli_compatible: yes
    networks:
      - name: "{{ playbook_network }}"
    state: started

- name: Mark as completed
  set_fact:
    sql_ready: true
  tags:
    - always
