---
# - name: Install required system packages
#   apt:
#     name: "{{ item }}"
#     state: latest
#     update_cache: yes
#   with_items: "{{ docker_setup_requirements }}"

# - name: Add Docker GPG apt Key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

# - name: Add Docker Repository
#   apt_repository:
#     repo: deb https://download.docker.com/linux/ubuntu bionic stable
#     state: present

# - name: Update apt and install docker-ce
#   apt:
#     name: docker-ce
#     state: latest
#     update_cache: yes

# - name: Start docker service
#   service:
#     name: docker
#     state: started

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Create Docker network
  docker_network:
    name: "{{ playbook_network }}"
    state: present

- name: Mark as completed
  set_fact:
    docker_ready: true
  tags:
    - always
